services:
  collector:
    image: otel/opentelemetry-collector
    container_name: collector
    restart: unless-stopped
    volumes:
      - ${pwd}/collector-config.yml:/etc/opentelemetry-collector/config.yml
    command: --config=/etc/opentelemetry-collector/config.yml
