services:
  collector:
    image: otel/opentelemetry-collector
    container_name: collector
    restart: unless-stopped
    volumes:
      - ./:/etc/opentelemetry-collector
    command: --config=/etc/opentelemetry-collector/config.yml
