services:
  collector:
    image: otel/opentelemetry-collector
    container_name: collector
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/opentelemetry-collector/config.yml
    command: --config=/etc/opentelemetry-collector/config.yml
